package com.wfc.test4.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table user.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String phone;
    private String name;
    private java.util.Date create_time;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String phone, String name, java.util.Date create_time) {
        this.id = id;
        this.phone = phone;
        this.name = name;
        this.create_time = create_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

}
